### ISSUE TITLE
Enhancement of Genie's Documentation

### ISSUE THREAD

**Issue by ALIPHATICHYD** [thenameisajay/Genie#1]
Hi there! I've been exploring the Genie-Rho app and noticed a few areas where we could enhance the documentation to make it even more informative and user-friendly.

Here are some suggestions:
Structural Refactoring
Troubleshooting: Address common issues and solutions.
Contributing: Explain how developers can contribute to the project.
Licence: Specify the project's licence to clarify usage rights.
FAQ: Answer frequently asked questions about the app's usage and limitations.

I'd be happy to contribute to drafting or editing these sections to make the documentation more comprehensive and helpful for both users and developers.

I'm open to any feedback or suggestions on how we can improve the documentation together. Thanks for considering these ideas!

**Comment by ajaymahadeven** [comment]
Hi @ALIPHATICHYD , I'd be happy to take your inputs and If you have any specific preferences regarding the collaboration platform or any additional ideas, please let me know. I'd be happy to work together to make the app documentation top-notch!

**Comment by ALIPHATICHYD** [comment]
I'm happy to put forward my inputs, so can I be assigned to this issue so I can get started.

**Comment by ajaymahadeven** [comment]
@ALIPHATICHYD  I've assigned you to the issue, feel free to contact me on any necessities.

**Comment by ALIPHATICHYD** [comment]
Thank you very much 
I'll begin working on it, so you'll be expecting my input soon.

**Comment by ALIPHATICHYD** [comment]
I guess this issue is due for closure. If there are any other features you'd like to work on, I'd be happy to help.
It was nice to contribute to this project.
Thank you very much

**Comment by ajaymahadeven** [comment]
@ALIPHATICHYD .. The application would benefit from  (https://ai.google.dev/docs/prompt_best_practices?authuser=1#experiment-with-different-parameter-values)... I've already added max Tokens but I've been busy with work and other projects.
I was planning to add : 
> Temperature
> Top-K
> Top-P

If you have any other suggestions  or new feature , please do.

**Comment by ALIPHATICHYD** [comment]
Oh 
I'm glad you told me that 
I'll check it out and see what I can add concerning these three.
Temperature
Top-K
Top-P
